{
  "formatVersion": "1.1",
  "component": {
    "group": "org.curioswitch.curiostack",
    "module": "protobuf-jackson",
    "version": "1.2.0.10-fix-enum",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "oorpwoyp35g4zfduvjtsptyejq"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.curioswitch.curiostack",
          "module": "curiostack-bom",
          "version": {
            "requires": "0.7.0"
          },
          "excludes": [
            {
              "group": "com.google.guava",
              "module": "guava-jdk5"
            }
          ],
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.12.1"
          },
          "excludes": [
            {
              "group": "com.google.guava",
              "module": "guava-jdk5"
            }
          ]
        },
        {
          "group": "com.google.protobuf",
          "module": "protobuf-java",
          "version": {
            "requires": "3.15.3"
          },
          "excludes": [
            {
              "group": "com.google.guava",
              "module": "guava-jdk5"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "protobuf-jackson-1.2.0.10-fix-enum.jar",
          "url": "protobuf-jackson-1.2.0.10-fix-enum.jar",
          "size": 104494,
          "sha512": "ffa31e14f1bb5d427825b45e5f6abddf9c0bf8ec92048972072c5d21ce126bb41a924a193693d16512ba1e53fe719a3fcd676c4b9149eb33c89e1d90740a72f9",
          "sha256": "c8656659658fb4610cf3e1376b58ba91265fabe9a9a193c75bfffc54a493b4a8",
          "sha1": "90d1ca985ddc3f8704cd9dcca4180221ad40e31c",
          "md5": "9f1eeda543b795a5267505ef807a4e55"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "jakarta.annotation",
          "module": "jakarta.annotation-api",
          "version": {
            "requires": "1.3.5"
          },
          "excludes": [
            {
              "group": "com.google.guava",
              "module": "guava-jdk5"
            }
          ]
        },
        {
          "group": "net.bytebuddy",
          "module": "byte-buddy",
          "version": {
            "requires": "1.10.20"
          },
          "excludes": [
            {
              "group": "com.google.guava",
              "module": "guava-jdk5"
            }
          ]
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1-jre"
          },
          "excludes": [
            {
              "group": "com.google.guava",
              "module": "guava-jdk5"
            }
          ]
        },
        {
          "group": "org.curioswitch.curiostack",
          "module": "curiostack-bom",
          "version": {
            "requires": "0.7.0"
          },
          "excludes": [
            {
              "group": "com.google.guava",
              "module": "guava-jdk5"
            }
          ],
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.12.1"
          },
          "excludes": [
            {
              "group": "com.google.guava",
              "module": "guava-jdk5"
            }
          ]
        },
        {
          "group": "com.google.protobuf",
          "module": "protobuf-java",
          "version": {
            "requires": "3.15.3"
          },
          "excludes": [
            {
              "group": "com.google.guava",
              "module": "guava-jdk5"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "protobuf-jackson-1.2.0.10-fix-enum.jar",
          "url": "protobuf-jackson-1.2.0.10-fix-enum.jar",
          "size": 104494,
          "sha512": "ffa31e14f1bb5d427825b45e5f6abddf9c0bf8ec92048972072c5d21ce126bb41a924a193693d16512ba1e53fe719a3fcd676c4b9149eb33c89e1d90740a72f9",
          "sha256": "c8656659658fb4610cf3e1376b58ba91265fabe9a9a193c75bfffc54a493b4a8",
          "sha1": "90d1ca985ddc3f8704cd9dcca4180221ad40e31c",
          "md5": "9f1eeda543b795a5267505ef807a4e55"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "protobuf-jackson-1.2.0.10-fix-enum-javadoc.jar",
          "url": "protobuf-jackson-1.2.0.10-fix-enum-javadoc.jar",
          "size": 114526,
          "sha512": "d311d5b628ff7926b1c3993bb6baf44a3a0b4da6f3312e9934254c43c996d4577ccd464e58db2119d07994765ac15bf218d56450c6a303762c0c350b69198281",
          "sha256": "9fa55f3342584a244db85b2f2ca8be96aaca108af6e2a024317397a806960087",
          "sha1": "3d3912769a3d6cb9199f9a0a7be7dfa2fb637740",
          "md5": "19cc68ab319548d8b0ce10af22952cf4"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "protobuf-jackson-1.2.0.10-fix-enum-sources.jar",
          "url": "protobuf-jackson-1.2.0.10-fix-enum-sources.jar",
          "size": 64136,
          "sha512": "f31f43b8a60bea622bf576ec7300d198ae5e59aaa3e254a587bd77847e54ff888819c6b7df6a54ab8336023e8cf2b9c853495ea0729f8bdf623285c4be803ef3",
          "sha256": "089fafb89994c17801d06c9df00c3a032a4967c5f0300cf62de1eeb5442d1d97",
          "sha1": "fa4352b31bd30bbc6adee3648519343af73a51d1",
          "md5": "19cccfae73b73a6eedd9189965f6b20b"
        }
      ]
    }
  ]
}
