{
  "formatVersion": "1.1",
  "component": {
    "group": "org.curioswitch.curiostack",
    "module": "protobuf-jackson",
    "version": "1.2.0-fix-enum",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "vculqiurxrgw5kdskqbqdk3jua"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.curioswitch.curiostack",
          "module": "curiostack-bom",
          "version": {
            "requires": "0.7.0"
          },
          "excludes": [
            {
              "group": "com.google.guava",
              "module": "guava-jdk5"
            }
          ],
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.12.1"
          },
          "excludes": [
            {
              "group": "com.google.guava",
              "module": "guava-jdk5"
            }
          ]
        },
        {
          "group": "com.google.protobuf",
          "module": "protobuf-java",
          "version": {
            "requires": "3.15.3"
          },
          "excludes": [
            {
              "group": "com.google.guava",
              "module": "guava-jdk5"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "protobuf-jackson-1.2.0-fix-enum.jar",
          "url": "protobuf-jackson-1.2.0-fix-enum.jar",
          "size": 103719,
          "sha512": "df361e8f46a7bcba0832e0a8a18ee7df516d81736723fae08d315efef1043a04db66b9a247be4a189f8a990190dee09a5dd0087c8602e3bd6ea28e7917eb7941",
          "sha256": "353a26eda6da716c4a645a0d17bf0f8fd68f3a1b15b1dd28725542eeefda5d1c",
          "sha1": "7ef7fded367090e0c460284ee8ee50c4d0141828",
          "md5": "caacc7655da2cf8e081204f0021bac84"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "jakarta.annotation",
          "module": "jakarta.annotation-api",
          "version": {
            "requires": "1.3.5"
          },
          "excludes": [
            {
              "group": "com.google.guava",
              "module": "guava-jdk5"
            }
          ]
        },
        {
          "group": "net.bytebuddy",
          "module": "byte-buddy",
          "version": {
            "requires": "1.10.20"
          },
          "excludes": [
            {
              "group": "com.google.guava",
              "module": "guava-jdk5"
            }
          ]
        },
        {
          "group": "org.curioswitch.curiostack",
          "module": "curiostack-bom",
          "version": {
            "requires": "0.7.0"
          },
          "excludes": [
            {
              "group": "com.google.guava",
              "module": "guava-jdk5"
            }
          ],
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.12.1"
          },
          "excludes": [
            {
              "group": "com.google.guava",
              "module": "guava-jdk5"
            }
          ]
        },
        {
          "group": "com.google.protobuf",
          "module": "protobuf-java",
          "version": {
            "requires": "3.15.3"
          },
          "excludes": [
            {
              "group": "com.google.guava",
              "module": "guava-jdk5"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "protobuf-jackson-1.2.0-fix-enum.jar",
          "url": "protobuf-jackson-1.2.0-fix-enum.jar",
          "size": 103719,
          "sha512": "df361e8f46a7bcba0832e0a8a18ee7df516d81736723fae08d315efef1043a04db66b9a247be4a189f8a990190dee09a5dd0087c8602e3bd6ea28e7917eb7941",
          "sha256": "353a26eda6da716c4a645a0d17bf0f8fd68f3a1b15b1dd28725542eeefda5d1c",
          "sha1": "7ef7fded367090e0c460284ee8ee50c4d0141828",
          "md5": "caacc7655da2cf8e081204f0021bac84"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "protobuf-jackson-1.2.0-fix-enum-javadoc.jar",
          "url": "protobuf-jackson-1.2.0-fix-enum-javadoc.jar",
          "size": 114487,
          "sha512": "7bfa50e942e9b4499709979e410807830723f491fb1baaadf4ec9eba4a45b5c05357c1236e427fdda644d5d0f2f3b178e26b85cad0823f25146996f38f9d0e64",
          "sha256": "14a7da264d50b57480431a8a953f4a2891ac4778938bc61b645e982adf4501bd",
          "sha1": "33ae0eac88b70679d900ffb859672e60e9229cb1",
          "md5": "befbd5a677cb0ff2bc9362ef715265a6"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "protobuf-jackson-1.2.0-fix-enum-sources.jar",
          "url": "protobuf-jackson-1.2.0-fix-enum-sources.jar",
          "size": 63834,
          "sha512": "b5c0edc23dcea2b5f46611fe78d55b9b1402e54cb7fbbba58d27bcfacc20daac2389a9436b3c28473f210fb26106c38a02bb2bbc701c7b182c877d0bc3207451",
          "sha256": "85901709790137e677c390e41d4802ed99f0336cbb2686faef81401b51780fc3",
          "sha1": "45c41b8edef416c5a30b2f6d73467ad385b230da",
          "md5": "f671a1ac1cca6d520b574d6bf875e38b"
        }
      ]
    }
  ]
}
