{
  "formatVersion": "1.1",
  "component": {
    "group": "org.curioswitch.curiostack",
    "module": "protobuf-jackson",
    "version": "1.2.0.6-fix-enum",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "fafa346c7vel3ov75c6xov43qu"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.curioswitch.curiostack",
          "module": "curiostack-bom",
          "version": {
            "requires": "0.7.0"
          },
          "excludes": [
            {
              "group": "com.google.guava",
              "module": "guava-jdk5"
            }
          ],
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.12.1"
          },
          "excludes": [
            {
              "group": "com.google.guava",
              "module": "guava-jdk5"
            }
          ]
        },
        {
          "group": "com.google.protobuf",
          "module": "protobuf-java",
          "version": {
            "requires": "3.15.3"
          },
          "excludes": [
            {
              "group": "com.google.guava",
              "module": "guava-jdk5"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "protobuf-jackson-1.2.0.6-fix-enum.jar",
          "url": "protobuf-jackson-1.2.0.6-fix-enum.jar",
          "size": 103775,
          "sha512": "b05b9c6f7e12843512c8c4c8351422b8d56ec1c3cad31bd479677795e295ad3f2a8f991b0fdd66b2a84e4a458b1b9c72c9c153b38b26fe44a00894fd6bdd7234",
          "sha256": "122584075408762ee23b0d4c5d6fe524e44bb40598efe0598da08db65d7379f0",
          "sha1": "08fd2ef8e63394a63da30be6668d75ca2e5afc5a",
          "md5": "27e142fdf324fd7e8e55745186afe831"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "jakarta.annotation",
          "module": "jakarta.annotation-api",
          "version": {
            "requires": "1.3.5"
          },
          "excludes": [
            {
              "group": "com.google.guava",
              "module": "guava-jdk5"
            }
          ]
        },
        {
          "group": "net.bytebuddy",
          "module": "byte-buddy",
          "version": {
            "requires": "1.10.20"
          },
          "excludes": [
            {
              "group": "com.google.guava",
              "module": "guava-jdk5"
            }
          ]
        },
        {
          "group": "org.curioswitch.curiostack",
          "module": "curiostack-bom",
          "version": {
            "requires": "0.7.0"
          },
          "excludes": [
            {
              "group": "com.google.guava",
              "module": "guava-jdk5"
            }
          ],
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.12.1"
          },
          "excludes": [
            {
              "group": "com.google.guava",
              "module": "guava-jdk5"
            }
          ]
        },
        {
          "group": "com.google.protobuf",
          "module": "protobuf-java",
          "version": {
            "requires": "3.15.3"
          },
          "excludes": [
            {
              "group": "com.google.guava",
              "module": "guava-jdk5"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "protobuf-jackson-1.2.0.6-fix-enum.jar",
          "url": "protobuf-jackson-1.2.0.6-fix-enum.jar",
          "size": 103775,
          "sha512": "b05b9c6f7e12843512c8c4c8351422b8d56ec1c3cad31bd479677795e295ad3f2a8f991b0fdd66b2a84e4a458b1b9c72c9c153b38b26fe44a00894fd6bdd7234",
          "sha256": "122584075408762ee23b0d4c5d6fe524e44bb40598efe0598da08db65d7379f0",
          "sha1": "08fd2ef8e63394a63da30be6668d75ca2e5afc5a",
          "md5": "27e142fdf324fd7e8e55745186afe831"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "protobuf-jackson-1.2.0.6-fix-enum-javadoc.jar",
          "url": "protobuf-jackson-1.2.0.6-fix-enum-javadoc.jar",
          "size": 114516,
          "sha512": "aa392d995a3190098a622a0423ff2d73b5c714e2cf8922956e8186790df71bfe08c9681d502cdf2cafc1a0219a96e3828293b23c725cc350804ebd007e912f63",
          "sha256": "0b240f83350bd61fa1508118d706f2d2c76fbc35ed0545405e5425776fd6c8ff",
          "sha1": "d6191bcd816c5fc56e08b41d9950117ba2231987",
          "md5": "698990fa298e217d4c2c0e362290b044"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "protobuf-jackson-1.2.0.6-fix-enum-sources.jar",
          "url": "protobuf-jackson-1.2.0.6-fix-enum-sources.jar",
          "size": 63855,
          "sha512": "22ece2ec3d46ed1078c137ee618149eb9b394f5316d058a901fdfbc039c203c60c9a8d39c9be8a8415cf28d57d4d0f994452ee134305c1a51718a18ec120f40b",
          "sha256": "155a5df2d0b40f8613babd05e1f15b016f87663a4290c73ff032420dd4b5c103",
          "sha1": "3726eb66773445ea30105e12eb3f074d3ded2ac1",
          "md5": "5bf6c3cd4feb9533defcfe3518c4310b"
        }
      ]
    }
  ]
}
