{
  "formatVersion": "1.1",
  "component": {
    "group": "org.curioswitch.curiostack",
    "module": "protobuf-jackson",
    "version": "1.2.0.8-fix-enum",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "4bakty7wurcfpexmojrafdsiuu"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.curioswitch.curiostack",
          "module": "curiostack-bom",
          "version": {
            "requires": "0.7.0"
          },
          "excludes": [
            {
              "group": "com.google.guava",
              "module": "guava-jdk5"
            }
          ],
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.12.1"
          },
          "excludes": [
            {
              "group": "com.google.guava",
              "module": "guava-jdk5"
            }
          ]
        },
        {
          "group": "com.google.protobuf",
          "module": "protobuf-java",
          "version": {
            "requires": "3.15.3"
          },
          "excludes": [
            {
              "group": "com.google.guava",
              "module": "guava-jdk5"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "protobuf-jackson-1.2.0.8-fix-enum.jar",
          "url": "protobuf-jackson-1.2.0.8-fix-enum.jar",
          "size": 104308,
          "sha512": "ca010e5521713655e818e521a24811500719e9de8cdc0d29483fbd9aaf45b28d9730a8e8a3486bd9fee041056fb8def0bfc5ce2ee165d78af103db924c4d8795",
          "sha256": "a2f27486b6866a8f2db5f5378d30cdf0c76bd0feba19c1f405d987d50cd5c211",
          "sha1": "c278e3faaabaed7cf8ad2bd42908f170370cab0a",
          "md5": "89739bb36415d4ca452acf022abaa568"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "jakarta.annotation",
          "module": "jakarta.annotation-api",
          "version": {
            "requires": "1.3.5"
          },
          "excludes": [
            {
              "group": "com.google.guava",
              "module": "guava-jdk5"
            }
          ]
        },
        {
          "group": "net.bytebuddy",
          "module": "byte-buddy",
          "version": {
            "requires": "1.10.20"
          },
          "excludes": [
            {
              "group": "com.google.guava",
              "module": "guava-jdk5"
            }
          ]
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1-jre"
          },
          "excludes": [
            {
              "group": "com.google.guava",
              "module": "guava-jdk5"
            }
          ]
        },
        {
          "group": "org.curioswitch.curiostack",
          "module": "curiostack-bom",
          "version": {
            "requires": "0.7.0"
          },
          "excludes": [
            {
              "group": "com.google.guava",
              "module": "guava-jdk5"
            }
          ],
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.12.1"
          },
          "excludes": [
            {
              "group": "com.google.guava",
              "module": "guava-jdk5"
            }
          ]
        },
        {
          "group": "com.google.protobuf",
          "module": "protobuf-java",
          "version": {
            "requires": "3.15.3"
          },
          "excludes": [
            {
              "group": "com.google.guava",
              "module": "guava-jdk5"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "protobuf-jackson-1.2.0.8-fix-enum.jar",
          "url": "protobuf-jackson-1.2.0.8-fix-enum.jar",
          "size": 104308,
          "sha512": "ca010e5521713655e818e521a24811500719e9de8cdc0d29483fbd9aaf45b28d9730a8e8a3486bd9fee041056fb8def0bfc5ce2ee165d78af103db924c4d8795",
          "sha256": "a2f27486b6866a8f2db5f5378d30cdf0c76bd0feba19c1f405d987d50cd5c211",
          "sha1": "c278e3faaabaed7cf8ad2bd42908f170370cab0a",
          "md5": "89739bb36415d4ca452acf022abaa568"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "protobuf-jackson-1.2.0.8-fix-enum-javadoc.jar",
          "url": "protobuf-jackson-1.2.0.8-fix-enum-javadoc.jar",
          "size": 114513,
          "sha512": "4b388bdc3d5c825298c444516dd252ab8bdee48b84a1df5bf1871595ee94cc907f7724bf2a3eca260c89f1f68fe7376a6f4b0c0075ff99a2394b5ecaa26ae7b4",
          "sha256": "4dfa4e41606173c93bd1defefcb7ec5d52aaa27974defe9b37f7562d4bb78e62",
          "sha1": "cb61517f917061588dc35fcb3bb151fdc1894620",
          "md5": "6d794e88564469b63c5b028ead3438ee"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "protobuf-jackson-1.2.0.8-fix-enum-sources.jar",
          "url": "protobuf-jackson-1.2.0.8-fix-enum-sources.jar",
          "size": 64044,
          "sha512": "d26fbdf66b7b7def49cbb1cc4c7d6af98782dfeb69fe6f98d7fcfd8c49e60e4900a00b0abbbcd26b6a5825a8fefb6eec6501eaaf908999d71ce42c321d9c1430",
          "sha256": "46c74849641884df0d0f97fc40e5f31b216d2dfe7f7004ea353ea5ae68655f0e",
          "sha1": "a03f2fae837213ceee733ee8867293a7c2a8196e",
          "md5": "d9499a6107c9c29724751cd74a7ce5f3"
        }
      ]
    }
  ]
}
