{
  "formatVersion": "1.1",
  "component": {
    "group": "org.curioswitch.curiostack",
    "module": "protobuf-jackson",
    "version": "1.2.0.2-fix-enum",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "lab2m2wbdzdinmho7i5ibd7ch4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.curioswitch.curiostack",
          "module": "curiostack-bom",
          "version": {
            "requires": "0.7.0"
          },
          "excludes": [
            {
              "group": "com.google.guava",
              "module": "guava-jdk5"
            }
          ],
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.12.1"
          },
          "excludes": [
            {
              "group": "com.google.guava",
              "module": "guava-jdk5"
            }
          ]
        },
        {
          "group": "com.google.protobuf",
          "module": "protobuf-java",
          "version": {
            "requires": "3.15.3"
          },
          "excludes": [
            {
              "group": "com.google.guava",
              "module": "guava-jdk5"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "protobuf-jackson-1.2.0.2-fix-enum.jar",
          "url": "protobuf-jackson-1.2.0.2-fix-enum.jar",
          "size": 103743,
          "sha512": "73a67f5c642753baa8280797f071b4b30406f0d669ba50ba2c215c3d93d94f228f17f8d53746bbe5ee279050eadb1cf432241753423a8f4395f8af21f64df464",
          "sha256": "1e9175c732dd54a47272d77e43eb7c816ce4154f48dab1061780faead024f7c9",
          "sha1": "dc07cd0fc2289ec6a1bfbbf44c8acecc5b973ae1",
          "md5": "e5110a63bbcf703de3c2ec5771420c57"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "jakarta.annotation",
          "module": "jakarta.annotation-api",
          "version": {
            "requires": "1.3.5"
          },
          "excludes": [
            {
              "group": "com.google.guava",
              "module": "guava-jdk5"
            }
          ]
        },
        {
          "group": "net.bytebuddy",
          "module": "byte-buddy",
          "version": {
            "requires": "1.10.20"
          },
          "excludes": [
            {
              "group": "com.google.guava",
              "module": "guava-jdk5"
            }
          ]
        },
        {
          "group": "org.curioswitch.curiostack",
          "module": "curiostack-bom",
          "version": {
            "requires": "0.7.0"
          },
          "excludes": [
            {
              "group": "com.google.guava",
              "module": "guava-jdk5"
            }
          ],
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.12.1"
          },
          "excludes": [
            {
              "group": "com.google.guava",
              "module": "guava-jdk5"
            }
          ]
        },
        {
          "group": "com.google.protobuf",
          "module": "protobuf-java",
          "version": {
            "requires": "3.15.3"
          },
          "excludes": [
            {
              "group": "com.google.guava",
              "module": "guava-jdk5"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "protobuf-jackson-1.2.0.2-fix-enum.jar",
          "url": "protobuf-jackson-1.2.0.2-fix-enum.jar",
          "size": 103743,
          "sha512": "73a67f5c642753baa8280797f071b4b30406f0d669ba50ba2c215c3d93d94f228f17f8d53746bbe5ee279050eadb1cf432241753423a8f4395f8af21f64df464",
          "sha256": "1e9175c732dd54a47272d77e43eb7c816ce4154f48dab1061780faead024f7c9",
          "sha1": "dc07cd0fc2289ec6a1bfbbf44c8acecc5b973ae1",
          "md5": "e5110a63bbcf703de3c2ec5771420c57"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "protobuf-jackson-1.2.0.2-fix-enum-javadoc.jar",
          "url": "protobuf-jackson-1.2.0.2-fix-enum-javadoc.jar",
          "size": 114510,
          "sha512": "b4f5cf4e48743e362f2a72ad49b75828d462f237e120a7ccfcdc2a7bff8326815b1fbfb883a4ed79429047ce946a8e25c2c586cefcc281f7b83517d91135e6bf",
          "sha256": "fdee6312b50a80ea24fce81d54c53e3cb7e74d5eeb4342c43175c02df7765c2b",
          "sha1": "87e4fd73cbfce23b7917e28c89745127b33b7775",
          "md5": "c3e237a378a83ace4d96cd266d1ffb9d"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "protobuf-jackson-1.2.0.2-fix-enum-sources.jar",
          "url": "protobuf-jackson-1.2.0.2-fix-enum-sources.jar",
          "size": 63848,
          "sha512": "9828e6a8518623b87aee04b400c459ddd3150d14f923b195bafd55fa45511ec625c1f8fe0e888ae7163c46b3000c40a1998f9a3f7db389e79f78a85424d35781",
          "sha256": "194b8785531943a1365252d3cfe37a32fde5843a2fe1be95b67fdfcbe7c308ba",
          "sha1": "6cdd57c901dd0618f5adfdfbaca6987470b4ce7a",
          "md5": "d26899026495b103d8620d7e061b10b9"
        }
      ]
    }
  ]
}
