{
  "formatVersion": "1.1",
  "component": {
    "group": "org.curioswitch.curiostack",
    "module": "protobuf-jackson",
    "version": "1.1.0.1-support-proto2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "hqvowshdyfcvtk2lhuqrsk4viq"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.curioswitch.curiostack",
          "module": "curiostack-bom",
          "version": {
            "requires": "0.6.0"
          },
          "excludes": [
            {
              "group": "com.google.guava",
              "module": "guava-jdk5"
            }
          ],
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.12.0"
          },
          "excludes": [
            {
              "group": "com.google.guava",
              "module": "guava-jdk5"
            }
          ]
        },
        {
          "group": "com.google.protobuf",
          "module": "protobuf-java",
          "version": {
            "requires": "3.14.0"
          },
          "excludes": [
            {
              "group": "com.google.guava",
              "module": "guava-jdk5"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "protobuf-jackson-1.1.0.1-support-proto2.jar",
          "url": "protobuf-jackson-1.1.0.1-support-proto2.jar",
          "size": 98611,
          "sha512": "7c2a29772a8de1a6c1117631a73c38e80ee940ff95c09f9fb6b5de7417a1f024885af1a2791e5024204e0163f3bfd5fcdd8560649d688119919028f489d41b5e",
          "sha256": "73fea011bdcb04a5a0a679f2bcf224843712ba5fccc146bec37aa11de3843e94",
          "sha1": "b5413b706a7c6d0dce676c2879c57ae2b9fffece",
          "md5": "4d942564e2307aeeb680cb4835598756"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "jakarta.annotation",
          "module": "jakarta.annotation-api",
          "version": {
            "requires": "1.3.5"
          },
          "excludes": [
            {
              "group": "com.google.guava",
              "module": "guava-jdk5"
            }
          ]
        },
        {
          "group": "com.google.protobuf",
          "module": "protobuf-java-util",
          "version": {
            "requires": "3.14.0"
          },
          "excludes": [
            {
              "group": "com.google.guava",
              "module": "guava-jdk5"
            }
          ]
        },
        {
          "group": "net.bytebuddy",
          "module": "byte-buddy",
          "version": {
            "requires": "1.10.18"
          },
          "excludes": [
            {
              "group": "com.google.guava",
              "module": "guava-jdk5"
            }
          ]
        },
        {
          "group": "org.curioswitch.curiostack",
          "module": "curiostack-bom",
          "version": {
            "requires": "0.6.0"
          },
          "excludes": [
            {
              "group": "com.google.guava",
              "module": "guava-jdk5"
            }
          ],
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.12.0"
          },
          "excludes": [
            {
              "group": "com.google.guava",
              "module": "guava-jdk5"
            }
          ]
        },
        {
          "group": "com.google.protobuf",
          "module": "protobuf-java",
          "version": {
            "requires": "3.14.0"
          },
          "excludes": [
            {
              "group": "com.google.guava",
              "module": "guava-jdk5"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "protobuf-jackson-1.1.0.1-support-proto2.jar",
          "url": "protobuf-jackson-1.1.0.1-support-proto2.jar",
          "size": 98611,
          "sha512": "7c2a29772a8de1a6c1117631a73c38e80ee940ff95c09f9fb6b5de7417a1f024885af1a2791e5024204e0163f3bfd5fcdd8560649d688119919028f489d41b5e",
          "sha256": "73fea011bdcb04a5a0a679f2bcf224843712ba5fccc146bec37aa11de3843e94",
          "sha1": "b5413b706a7c6d0dce676c2879c57ae2b9fffece",
          "md5": "4d942564e2307aeeb680cb4835598756"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "protobuf-jackson-1.1.0.1-support-proto2-javadoc.jar",
          "url": "protobuf-jackson-1.1.0.1-support-proto2-javadoc.jar",
          "size": 114535,
          "sha512": "37c655a25f8558a1ffff35215982c1d4b1027f35fe6b8c12efc911049fb02b099d74434276bac20275dd0b90a3fa678bd1b98a10f69d44d1b365003ad6cbd1c7",
          "sha256": "1125043ffd8e40d4c1d4d8ab11b43d339ad6b6976ba2990678ef1252fdcf69fb",
          "sha1": "55e44d27657284f2be4b1161acb4f648ee6b30a9",
          "md5": "0673d4d232fc4f9c29593ffbc776554d"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "protobuf-jackson-1.1.0.1-support-proto2-sources.jar",
          "url": "protobuf-jackson-1.1.0.1-support-proto2-sources.jar",
          "size": 59594,
          "sha512": "27073a04edc2ee53861c55a6501791676fb58d4fcefccc70eeb8163feb6f63afa08501bbf19e6155df4b9a863c340ceed6b8bdd6ccc9cc0e05eee31aa62464c1",
          "sha256": "d2afc0d86abc2bb48c5314a95160b07ae445452be98ff4bed97f36300a4182af",
          "sha1": "6d341bd261be28e589319b737d04d80910b05875",
          "md5": "de2766dc9726ad925ef136678fe284d0"
        }
      ]
    }
  ]
}
