{
  "formatVersion": "1.1",
  "component": {
    "group": "org.curioswitch.curiostack",
    "module": "protobuf-jackson",
    "version": "1.2.0.7-fix-enum",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "aezx3rbn2zdsllkj5gw6umvts4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.curioswitch.curiostack",
          "module": "curiostack-bom",
          "version": {
            "requires": "0.7.0"
          },
          "excludes": [
            {
              "group": "com.google.guava",
              "module": "guava-jdk5"
            }
          ],
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.12.1"
          },
          "excludes": [
            {
              "group": "com.google.guava",
              "module": "guava-jdk5"
            }
          ]
        },
        {
          "group": "com.google.protobuf",
          "module": "protobuf-java",
          "version": {
            "requires": "3.15.3"
          },
          "excludes": [
            {
              "group": "com.google.guava",
              "module": "guava-jdk5"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "protobuf-jackson-1.2.0.7-fix-enum.jar",
          "url": "protobuf-jackson-1.2.0.7-fix-enum.jar",
          "size": 103835,
          "sha512": "9e74846ec7deea2781cba219b8f704c15993b0c9de2d4a8c13c4460d83f422f830ddd0ce2b67e00bf2c51b63b1aded163bd718540594afa4438484d5754fb358",
          "sha256": "bcbcccc49148aa39559d59966cca28ce25f713f632dd9cb35ec564d73c3fc159",
          "sha1": "5ff95bca886155e6b5ce139462d5b3fc9b7521e7",
          "md5": "d412f0d29cdacc46981eca36c0928630"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "jakarta.annotation",
          "module": "jakarta.annotation-api",
          "version": {
            "requires": "1.3.5"
          },
          "excludes": [
            {
              "group": "com.google.guava",
              "module": "guava-jdk5"
            }
          ]
        },
        {
          "group": "net.bytebuddy",
          "module": "byte-buddy",
          "version": {
            "requires": "1.10.20"
          },
          "excludes": [
            {
              "group": "com.google.guava",
              "module": "guava-jdk5"
            }
          ]
        },
        {
          "group": "org.curioswitch.curiostack",
          "module": "curiostack-bom",
          "version": {
            "requires": "0.7.0"
          },
          "excludes": [
            {
              "group": "com.google.guava",
              "module": "guava-jdk5"
            }
          ],
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.12.1"
          },
          "excludes": [
            {
              "group": "com.google.guava",
              "module": "guava-jdk5"
            }
          ]
        },
        {
          "group": "com.google.protobuf",
          "module": "protobuf-java",
          "version": {
            "requires": "3.15.3"
          },
          "excludes": [
            {
              "group": "com.google.guava",
              "module": "guava-jdk5"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "protobuf-jackson-1.2.0.7-fix-enum.jar",
          "url": "protobuf-jackson-1.2.0.7-fix-enum.jar",
          "size": 103835,
          "sha512": "9e74846ec7deea2781cba219b8f704c15993b0c9de2d4a8c13c4460d83f422f830ddd0ce2b67e00bf2c51b63b1aded163bd718540594afa4438484d5754fb358",
          "sha256": "bcbcccc49148aa39559d59966cca28ce25f713f632dd9cb35ec564d73c3fc159",
          "sha1": "5ff95bca886155e6b5ce139462d5b3fc9b7521e7",
          "md5": "d412f0d29cdacc46981eca36c0928630"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "protobuf-jackson-1.2.0.7-fix-enum-javadoc.jar",
          "url": "protobuf-jackson-1.2.0.7-fix-enum-javadoc.jar",
          "size": 114516,
          "sha512": "ce8747e627f2cc89531c3fdf0a0d88695a79609e86dcc0a85ea57078dbfbc6b7cc98a610a8b7db0f0afd1a2d8aac759917026522f9e29d2661ad83020325f493",
          "sha256": "bf51dbe9a956cd5a0d896600c96c833a952624701bcd368f556c4075c993dad1",
          "sha1": "90c8af3865cb3cec59c5cc6c1ed8104cd29644cc",
          "md5": "e2da249fb41bda85b42d04054fae13e8"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "protobuf-jackson-1.2.0.7-fix-enum-sources.jar",
          "url": "protobuf-jackson-1.2.0.7-fix-enum-sources.jar",
          "size": 63903,
          "sha512": "ed3e7346ca9bacdf95f6c468fa75232811ef597722e047c7ffb48e33eeb98b02ade837e8cc6b0d3a2ae5908617426a00e9ccb315f6d9e058c304f70cebd9dda6",
          "sha256": "83975728262999a20907eeb13a06f89fb2c5398ed3d32b3b584b0866d20130d3",
          "sha1": "8617eeeb95f6e6bf4f6d8f1e4a870f75db2b3cac",
          "md5": "0982e023e187c026dc3df8243c9728d3"
        }
      ]
    }
  ]
}
