{
  "formatVersion": "1.1",
  "component": {
    "group": "org.curioswitch.curiostack",
    "module": "protobuf-jackson",
    "version": "1.2.0.3-fix-enum",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "2xnp3ogstrh3ngpi7en2p35bga"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.curioswitch.curiostack",
          "module": "curiostack-bom",
          "version": {
            "requires": "0.7.0"
          },
          "excludes": [
            {
              "group": "com.google.guava",
              "module": "guava-jdk5"
            }
          ],
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.12.1"
          },
          "excludes": [
            {
              "group": "com.google.guava",
              "module": "guava-jdk5"
            }
          ]
        },
        {
          "group": "com.google.protobuf",
          "module": "protobuf-java",
          "version": {
            "requires": "3.15.3"
          },
          "excludes": [
            {
              "group": "com.google.guava",
              "module": "guava-jdk5"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "protobuf-jackson-1.2.0.3-fix-enum.jar",
          "url": "protobuf-jackson-1.2.0.3-fix-enum.jar",
          "size": 103722,
          "sha512": "088027d94fdad6262e63b478150c91939f661d5b9e18cb6a84b9d8c5062b4f05c87ec7a5ecc168c6c3457648da4f5a7fc633c93dc1e748a1a09e05fb4a3f10e8",
          "sha256": "a4f97696878516169153459b6c84b773e1921f7dff75a4162153ed30989c642c",
          "sha1": "1ab662a6da4f8bf74b0a533dce61afd7f41e7825",
          "md5": "7f23c9e71516c2461e856c5274e10afd"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "jakarta.annotation",
          "module": "jakarta.annotation-api",
          "version": {
            "requires": "1.3.5"
          },
          "excludes": [
            {
              "group": "com.google.guava",
              "module": "guava-jdk5"
            }
          ]
        },
        {
          "group": "net.bytebuddy",
          "module": "byte-buddy",
          "version": {
            "requires": "1.10.20"
          },
          "excludes": [
            {
              "group": "com.google.guava",
              "module": "guava-jdk5"
            }
          ]
        },
        {
          "group": "org.curioswitch.curiostack",
          "module": "curiostack-bom",
          "version": {
            "requires": "0.7.0"
          },
          "excludes": [
            {
              "group": "com.google.guava",
              "module": "guava-jdk5"
            }
          ],
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.12.1"
          },
          "excludes": [
            {
              "group": "com.google.guava",
              "module": "guava-jdk5"
            }
          ]
        },
        {
          "group": "com.google.protobuf",
          "module": "protobuf-java",
          "version": {
            "requires": "3.15.3"
          },
          "excludes": [
            {
              "group": "com.google.guava",
              "module": "guava-jdk5"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "protobuf-jackson-1.2.0.3-fix-enum.jar",
          "url": "protobuf-jackson-1.2.0.3-fix-enum.jar",
          "size": 103722,
          "sha512": "088027d94fdad6262e63b478150c91939f661d5b9e18cb6a84b9d8c5062b4f05c87ec7a5ecc168c6c3457648da4f5a7fc633c93dc1e748a1a09e05fb4a3f10e8",
          "sha256": "a4f97696878516169153459b6c84b773e1921f7dff75a4162153ed30989c642c",
          "sha1": "1ab662a6da4f8bf74b0a533dce61afd7f41e7825",
          "md5": "7f23c9e71516c2461e856c5274e10afd"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "protobuf-jackson-1.2.0.3-fix-enum-javadoc.jar",
          "url": "protobuf-jackson-1.2.0.3-fix-enum-javadoc.jar",
          "size": 114514,
          "sha512": "d8e58f751f65f4d7e324b22f32352c522e09d942121b31188501636a68e3298cfeac27b13dcf1095e2a0796555f6dec4c9c9d98fa9ccc685679cb20092c82fdd",
          "sha256": "3dac7a6eca89ff745a9728393f2b43f7eab3b778dbd9a3201d78585416e07483",
          "sha1": "4ffd247fa543a03ca29085c03051f3ff437b6e52",
          "md5": "21102d2f0a5d6a8c2324a790c56bd7b8"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "protobuf-jackson-1.2.0.3-fix-enum-sources.jar",
          "url": "protobuf-jackson-1.2.0.3-fix-enum-sources.jar",
          "size": 63840,
          "sha512": "83ce94a18fa45ad6c24fb9e652fac5938e67d064ce3da66afa9853bca3c8f4bf8e63d92376767a59592546cb711dd3331ed5259ac2947309c720c0611ad36b8d",
          "sha256": "a7932ae5e54e4da471a4972a8a41e6137e24da182dc532ebcfcba75b78b57a88",
          "sha1": "b5062b34faf4d087602c74aad37c9e4ed84b250b",
          "md5": "ccc2002e57d5aeed875a189500dc39f5"
        }
      ]
    }
  ]
}
