{
  "formatVersion": "1.1",
  "component": {
    "group": "org.curioswitch.curiostack",
    "module": "protobuf-jackson",
    "version": "1.2.0.5-fix-enum",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "2xqef3rpxre6vcknxjshx45ske"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.curioswitch.curiostack",
          "module": "curiostack-bom",
          "version": {
            "requires": "0.7.0"
          },
          "excludes": [
            {
              "group": "com.google.guava",
              "module": "guava-jdk5"
            }
          ],
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.12.1"
          },
          "excludes": [
            {
              "group": "com.google.guava",
              "module": "guava-jdk5"
            }
          ]
        },
        {
          "group": "com.google.protobuf",
          "module": "protobuf-java",
          "version": {
            "requires": "3.15.3"
          },
          "excludes": [
            {
              "group": "com.google.guava",
              "module": "guava-jdk5"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "protobuf-jackson-1.2.0.5-fix-enum.jar",
          "url": "protobuf-jackson-1.2.0.5-fix-enum.jar",
          "size": 103755,
          "sha512": "9a31f2c0f5f3ee3ce21eafcf4419a0731326c9fca4d10ed74a9ca16e007cb1886976f702e8c1cb2c223ee099bd58d0acf26b505836f210047f015e2582a6edd9",
          "sha256": "2675a0fa5d3912510be531efb8387940651edd8a216750db3963659492f0b6ff",
          "sha1": "42a9035294a8ab89c94ef38be0bd53a5cc93c7f7",
          "md5": "0c2333170b078832879254a1f5b823a8"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "jakarta.annotation",
          "module": "jakarta.annotation-api",
          "version": {
            "requires": "1.3.5"
          },
          "excludes": [
            {
              "group": "com.google.guava",
              "module": "guava-jdk5"
            }
          ]
        },
        {
          "group": "net.bytebuddy",
          "module": "byte-buddy",
          "version": {
            "requires": "1.10.20"
          },
          "excludes": [
            {
              "group": "com.google.guava",
              "module": "guava-jdk5"
            }
          ]
        },
        {
          "group": "org.curioswitch.curiostack",
          "module": "curiostack-bom",
          "version": {
            "requires": "0.7.0"
          },
          "excludes": [
            {
              "group": "com.google.guava",
              "module": "guava-jdk5"
            }
          ],
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.12.1"
          },
          "excludes": [
            {
              "group": "com.google.guava",
              "module": "guava-jdk5"
            }
          ]
        },
        {
          "group": "com.google.protobuf",
          "module": "protobuf-java",
          "version": {
            "requires": "3.15.3"
          },
          "excludes": [
            {
              "group": "com.google.guava",
              "module": "guava-jdk5"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "protobuf-jackson-1.2.0.5-fix-enum.jar",
          "url": "protobuf-jackson-1.2.0.5-fix-enum.jar",
          "size": 103755,
          "sha512": "9a31f2c0f5f3ee3ce21eafcf4419a0731326c9fca4d10ed74a9ca16e007cb1886976f702e8c1cb2c223ee099bd58d0acf26b505836f210047f015e2582a6edd9",
          "sha256": "2675a0fa5d3912510be531efb8387940651edd8a216750db3963659492f0b6ff",
          "sha1": "42a9035294a8ab89c94ef38be0bd53a5cc93c7f7",
          "md5": "0c2333170b078832879254a1f5b823a8"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "protobuf-jackson-1.2.0.5-fix-enum-javadoc.jar",
          "url": "protobuf-jackson-1.2.0.5-fix-enum-javadoc.jar",
          "size": 114514,
          "sha512": "aad00f81e32c75ee5f151923d77a240fcf77255b7d8c06b2fc9681566c4414671cd0c8d24c9e7caffac94930b06db27b63b5deaeec3d89c8f760026d215a0767",
          "sha256": "3af3ca2dede210c2722835f5a3dc08aadd8eeb0e006aab5c9d4406420e860d54",
          "sha1": "57b71693dd73fe9f34a68a3feaad57f2479e0e36",
          "md5": "6bb0748dc874d3613b5cb522de55d827"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "protobuf-jackson-1.2.0.5-fix-enum-sources.jar",
          "url": "protobuf-jackson-1.2.0.5-fix-enum-sources.jar",
          "size": 63854,
          "sha512": "1009b26e4865e2658540edd30c49018b9bea98ba42e3497a8c719df9ca2d6d62f624f6602af136720fb9a64ed0949c32f3b4ff3bcb09e7983af8450c9f97abc5",
          "sha256": "ba7d1ea7112013be0f7422f7abb48dc8955fc527d851c6fcb81ad12f7c46e03b",
          "sha1": "de15243e5faf916819f1073b99e3861fde87c527",
          "md5": "9c5e3b567f27af00de6efd3576160d5c"
        }
      ]
    }
  ]
}
